language: node_js

node_js: 14

jobs:
  include:
    - stage: Check code quality
      if: tag IS blank
      before_script:
        - npm install -g grunt-cli
        - sleep 10
      script:
        - grunt
